apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: postsync-

resources:
  - ../../base

patches:
  - path: patch-job.yml

configMapGenerator:
  - name: hook-config
    behavior: merge
    literals:
      - HOOK=PostSync
