---
apiVersion: v1
data:
  extraconfig-from-values.hcl: |-
    disable_mlock = true
    ui = true
    listener "tcp" {
      address = "[::]:8200"
      cluster_address = "[::]:8201"
      tls_cert_file = "/vault/userconfig/vault-secret/tls.crt"
      tls_key_file = "/vault/userconfig/vault-secret/tls.key"
    }
    storage "file" {
      path = "/vault/data"
    }
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/instance: vault
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: vault
    helm.sh/chart: vault-0.24.1
  name: vault-config
  namespace: vault
