apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - hook.yml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
  - name: hook-files
    files:
      - files/hook.sh
      - files/payload-template.json

  - name: hook-config
    literals:
      - HOOK=<todo>
      - APP_NAME=<todo>
      - ENVIRONMENT=<todo>
      - WEBHOOK_URL=<todo>



