apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vault

resources:
  - base
  - consolelink.yml

patches:
  - path: service-vault.patch.yml
  - path: service-vault-internal.patch.yml
